### ISSUE TITLE
Stuck in Authorize screen

### ISSUE THREAD

**Issue by sunnyaditya** [coinbase/coinbase-android-sdk-example#1]
<img width="338" alt="screen shot 2018-01-19 at 4 20 28 pm" src="https://user-images.githubusercontent.com/24604895/35147474-c1509178-fd34-11e7-9c03-4e2342e42f2b.png">

I was trying to your SDK example but it is not working . App stuck to Authorize screen. Please refer the attached screen shot. I have a coinbase account from India.

Please let me know if I am doing any mistake. I have changed the API Key and secret key with mine.

**Comment by abiemann** [comment]
Same here... just the AUTHORIZE screen over and over and over. Were you able to fix it ?

**Comment by abiemann** [comment]
I got it solved: your activity must `extends RoboActivity`, that means you have to update your build.gradle with roboguice as follows:

`    //  Coinbase SDK
    implementation ('org.roboguice:roboguice:2.0')
    implementation ('com.coinbase.android:coinbase-android-sdk:1.0.1'){
        exclude group: 'org.apache.httpcomponents', module:'httpclient'
    }`

If you don't want to add those two libraries to your project, then follow this tutorial on how to authenticate using retrofit: https://www.youtube.com/watch?v=TnQUb-ACqWs

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
