### ISSUE TITLE
No serializer found for class com.coinbase.api.entity.OAuthTokensRequest and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS)

### ISSUE THREAD

**Issue by adritung** [coinbase/coinbase-android-sdk-example#2]
Hello,

I have copied the code in the README and I'm getting this exception when running
`new CompleteAuthorizationTask(intent).execute();`

_No serializer found for class com.coinbase.api.entity.OAuthTokensRequest and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) )_

I'm using Android Studio with Gradle and have the following dependencies:
```
    compile 'org.roboguice:roboguice:3.0.1'
    compile 'com.coinbase.android:coinbase-android-sdk:1.0.1'
```

I've found a solution [here](http://www.baeldung.com/jackson-jsonmappingexception) but since I don't have access to the entity or the objectMapper it's not a valid solution on my side... Any ideas?

Thanks,
Adrian

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
